<?php

namespace FrontEnd\BackEndBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AchtralikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchtralikRepository extends EntityRepository
{

}
