<?php

namespace FrontEnd\BackEndBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryAtlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAtlRepository extends EntityRepository
{
}
